"""Persistence ports - business-facing contracts only."""
from __future__ import annotations

from typing import Any, Protocol


class PaymentMethodRepositoryPort(Protocol):
    async def list(self, customer_id: str, limit: int = 20, offset: int = 0) -> list[dict[str, Any]]: ...
    async def add(self, customer_id: str, type: str, provider: str, details_masked: dict[str, Any]) -> dict[str, Any] | None: ...
    async def set_default(self, customer_id: str, method_id: str) -> dict[str, Any] | None: ...
    async def remove(self, customer_id: str, method_id: str) -> bool: ...


class PreferenceRepositoryPort(Protocol):
    async def list(self, customer_id: str) -> list[dict[str, Any]]: ...
    async def set(self, customer_id: str, key: str, value: str) -> dict[str, Any] | None: ...


class SecurityRepositoryPort(Protocol):
    async def revoke_sessions(self, customer_id: str, reason: str) -> dict[str, Any] | None: ...
    async def change_password(self, customer_id: str, new_hash: str) -> bool: ...


class PrivacyRepositoryPort(Protocol):
    async def set_consent(self, customer_id: str, kind: str, consented: bool) -> dict[str, Any] | None: ...
    async def list_consents(self, customer_id: str) -> list[dict[str, Any]]: ...
    async def request_export(self, customer_id: str) -> dict[str, Any] | None: ...
    async def list_exports(self, customer_id: str, limit: int = 20, offset: int = 0) -> list[dict[str, Any]]: ...


class AccountClosureRepositoryPort(Protocol):
    async def schedule_closure(self, customer_id: str) -> dict[str, Any] | None: ...