"""LiabilityRepository — canonical persistence port for the liability aggregate."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class LiabilityRepository(Protocol):
    """Business persistence surface for owned liabilities."""

    async def get(self, user_id: str, liability_id: int) -> Any | None: ...
    async def add(self, params: dict[str, Any]) -> Any: ...
    async def update(self, user_id: str, params: dict[str, Any]) -> Any: ...
    async def restructure(self, user_id: str, params: dict[str, Any]) -> Any: ...
    async def archive(self, user_id: str, liability_id: int) -> Any: ...
    async def list(self, filters: dict[str, Any]) -> Any: ...
    async def summary(self, user_id: str) -> Any: ...