"""PropertyRepository — persistence port for the property domain.

Application services depend on THIS protocol; CUS.PROPERTY.* IDs live only
in PropertySqlAdapter.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PropertyRepository(Protocol):
    async def list(self, customer_id: str) -> list[dict[str, Any]]: ...
    async def get(self, customer_id: str, property_id: str) -> dict[str, Any] | None: ...
    async def create(self, customer_id: str, params: dict[str, Any]) -> dict[str, Any] | None: ...
    async def update(
        self, customer_id: str, property_id: str, params: dict[str, Any]
    ) -> dict[str, Any] | None: ...
    async def delete(self, customer_id: str, property_id: str) -> bool: ...
    async def add_room(
        self, customer_id: str, property_id: str, params: dict[str, Any]
    ) -> dict[str, Any] | None: ...
    async def remove_room(self, customer_id: str, room_id: str) -> bool: ...