"""ProviderAccountRepository — provider identity/credentials/auth port.

Mirrors CustomerRepository for the provider principal. Implemented by
ProviderAccountSqlAdapter; services depend only on this protocol.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProviderAccountRepository(Protocol):
    async def create(self, params: dict[str, Any]) -> Any | None: ...
    async def get_by_email(self, email: str) -> Any | None: ...
    async def get_by_id(self, user_id: str) -> Any | None: ...
    async def mark_verified(self, user_id: str, *, email: bool, phone: bool) -> Any | None: ...
    async def update_password(self, user_id: str, password_hash: str) -> Any | None: ...
    async def issue_otp(
        self, user_id: str, channel: str, purpose: str, code_hash: str, ttl_minutes: int
    ) -> Any | None: ...
    async def verify_otp(self, user_id: str, purpose: str, code_hash: str) -> bool: ...
    async def session_create(
        self, user_id: str, refresh_token_hash: str, device_info: str, ip_address: str, ttl_seconds: int
    ) -> Any | None: ...
    async def session_get_valid(self, refresh_token_hash: str) -> Any | None: ...
    async def session_revoke(self, refresh_token_hash: str) -> Any | None: ...
    async def session_revoke_all(self, user_id: str) -> Any | None: ...