"""PublicContentRepository — read-only port for public (unauthenticated) content."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class PublicContentRepository(Protocol):
    async def content_blocks(self) -> list[dict[str, Any]]: ...
    async def categories(self) -> list[dict[str, Any]]: ...
    async def services(self, category_code: str | None) -> list[dict[str, Any]]: ...
    async def search_services(self, term: str) -> list[dict[str, Any]]: ...
    async def faqs(self) -> list[dict[str, Any]]: ...