"""SessionRepository — refresh-token session persistence port."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SessionRepository(Protocol):
    async def create(self, params: dict[str, Any]) -> Any | None: ...
    async def get_valid(self, refresh_token_hash: str) -> Any | None: ...
    async def revoke(self, refresh_token_hash: str) -> Any | None: ...
    async def revoke_all(self, user_id: str) -> Any | None: ...