"""TransactionRepository — canonical persistence port for financial transactions."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TransactionRepository(Protocol):
    """Business persistence surface for owned transactions."""

    async def get(self, user_id: str, transaction_id: int) -> Any | None: ...
    async def add(self, params: dict[str, Any]) -> Any: ...
    async def update(self, user_id: str, params: dict[str, Any]) -> Any: ...
    async def settle(self, user_id: str, transaction_id: int) -> Any: ...
    async def archive(self, user_id: str, transaction_id: int) -> Any: ...
    async def list(self, filters: dict[str, Any]) -> Any: ...
    async def summary(self, user_id: str, period: str) -> Any: ...