"""Wallet / promotion / loyalty ports — business-facing contracts (Phase 12)."""
from __future__ import annotations

from typing import Any, Protocol


class WalletRepositoryPort(Protocol):
    async def ensure(self, customer_id: str) -> dict[str, Any] | None: ...
    async def get_balance(self, customer_id: str) -> dict[str, Any] | None: ...
    async def list_transactions(self, customer_id: str, limit: int, offset: int) -> list[dict[str, Any]]: ...
    async def credit(self, customer_id: str, amount: float) -> dict[str, Any] | None: ...
    async def debit(self, customer_id: str, amount: float) -> dict[str, Any] | None: ...


class PromotionRepositoryPort(Protocol):
    async def list_active(self, limit: int, offset: int) -> list[dict[str, Any]]: ...
    async def validate(self, code: str, amount: float) -> dict[str, Any] | None: ...
    async def use(self, promo_id: str) -> dict[str, Any] | None: ...


class LoyaltyRepositoryPort(Protocol):
    async def ensure(self, customer_id: str) -> dict[str, Any] | None: ...
    async def get_account(self, customer_id: str) -> dict[str, Any] | None: ...
    async def list_transactions(self, customer_id: str, limit: int, offset: int) -> list[dict[str, Any]]: ...
    async def earn(self, customer_id: str, points: float, activity: str, reference_id: str | None) -> dict[str, Any] | None: ...
    async def spend(self, customer_id: str, points: float, activity: str, reference_id: str | None) -> dict[str, Any] | None: ...